{
 "title": "Order API",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "uri",
    "label": "URI",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{application=\"$application\"}, uri)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Orders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Order Line Items",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(order_line_item_created_total[$__rate_interval])) by (name, milk, size)",
     "legendFormat": "{{name}} {{milk}} {{size}}"
    }
   ]
  },
  {
   "title": "Orders In Preparation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(order_line_item_total[$__rate_interval])) by (name, milk, size)",
     "legendFormat": "{{name}} {{milk}} {{size}}"
    }
   ]
  },
  {
   "title": "Orders Created",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(order_make_total[$__rate_interval])) by (location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Orders Taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(order_taken_total[$__rate_interval]))",
     "legendFormat": "{{name}} {{milk}} {{size}}"
    }
   ]
  },
  {
   "title": "Orders Prepared",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(order_prepared_total[$__rate_interval]))",
     "legendFormat": "{{name}} {{milk}} {{size}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "$application latency for $uri",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.00, sum(rate(http_server_requests_seconds_bucket{application=~\"$application\", uri=~\"$uri\"}[$__rate_interval])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=~\"$application\", uri=~\"$uri\"}[$__rate_interval])) by (le))",
     "legendFormat": "tp99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=~\"$application\", uri=~\"$uri\"}[$__rate_interval])) by (le))",
     "legendFormat": "tp95"
    }
   ]
  },
  {
   "title": "$application throughput for $uri",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=~\"$application\", uri=~\"$uri\"}[$__rate_interval])) by (outcome)",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "$application latency heatmap for $uri",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_bucket{application=~\"$application\", uri=~\"$uri\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}