{
 "title": "Spring Modulith",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "module_name", "query": { "query": "label_values(module_key)" } }
  ]
 },
 "panels": [
  { "title": "Per module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error rate per module (requests / second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(module_requests_seconds_count{error!=\"none\", module_key=\"$module_name\"}[$__rate_interval])",
     "legendFormat": "{{module_key}}"
    }
   ]
  },
  {
   "title": "Rate of module requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(module_requests_seconds_count{error=\"none\", module_key=\"$module_name\"}[$__rate_interval])",
     "legendFormat": "{{module_key}}"
    }
   ]
  },
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total processed events",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modulith_events_processed_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(modulith_events_processed_total[$__rate_interval])",
     "legendFormat": "{{EVENT_TYPE}}@{{MODULE_NAME}}"
    }
   ]
  }
 ]
}